# Generated by Django 3.1.7 on 2021-06-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='picture',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='media/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='glass',
            name='picture',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='media/', verbose_name='Picture'),
        ),
    ]
